### ISSUE TITLE
Error after uninstall

### ISSUE THREAD

**Issue by Marie-Antoinette** [alexanderjeurissen/ranger_devicons#42] opened 2019-04-26 12:42 UTC
I tryed your tool then make uninstall, now when I quit ranger I have this message:
**Invalid linemode: devicons; should be metatitle/permissions/fileinfo/filename**

Thks

**Comment by alexanderjeurissen** [comment] 2019-04-29 19:03
Hmm, it looks like the devicons linemode is still specified in the ranger configuration.

can you verify for me that `default_linemode devicons`
is no longer present in your `rc.conf` file ?

**Comment by alexanderjeurissen** [comment] 2019-04-29 19:06
I was able to reproduce the issue you outlined.
The reason this happens is because the `make uninstall` only removes the plugin files it does not remove the line in your `rc.conf` that sets the default linemode.

I'll add a section to the documentation to make sure this is documented.

**Comment by alexanderjeurissen** [comment] 2019-04-29 19:17
I weant ahead and expiremented with the makefile.
I updated the makefile to properly remove the `default_linemode` option that are added during installation whenever `make uninstall` is run.

**Comment by alexanderjeurissen** [comment] 2019-04-29 19:18
Changes are merged in, if you pull the latest master and run `make uninstall` the error should be resolved. feel free to reopen this issue if you run into any issues.

**Closed** 2019-04-29 19:17 UTC
