### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by chupy35** [alexanderjeurissen/ranger_devicons#30] opened 2018-11-11 20:43 UTC
i Install the full package of nerd-fonts in archlinux, using currently ProFont Windows.
Only some icons show off:

![screen](https://user-images.githubusercontent.com/892664/48318036-86a54c80-e5c8-11e8-8b7e-5b71be21bd8e.png)

**Comment by alexanderjeurissen** [comment] 2018-11-13 00:07
In order for me to get a better sense what the root cause of this might be, can you install the SourceCodePro font from the nerd-fonts library ? and see if you can reproduce the issue with that font as well ?

**Comment by chupy35** [comment] 2018-11-13 00:13
> In order for me to get a better sense what the root cause of this might be, can you install the SourceCodePro font from the nerd-fonts library ? and see if you can reproduce the issue with that font as well ?

Yes, i tried already with that font, I installed all the fonts from the package, its only happening with the folders i think, do you think is related that my sistem is in spanish? is only with folders.

**Comment by Daniel-Liu-c0deb0t** [comment] 2018-11-17 01:17
I installed the full zip package of the patched Fira (Fura) Code, and got the same problem.

However, I found a fix. In my font browser, it shows both Fura Code Nerd Font and Fura Code NF. Originally, I selected the former, and the folders did not show. But when I tried the latter font, and it works. Maybe you can try abbreviating Nerd Font to NF and see if it works?

**Comment by chupy35** [comment] 2018-11-22 23:02
> I installed the full zip package of the patched Fira (Fura) Code, and got the same problem.
> 
> However, I found a fix. In my font browser, it shows both Fura Code Nerd Font and Fura Code NF. Originally, I selected the former, and the folders did not show. But when I tried the latter font, and it works. Maybe you can try abbreviating Nerd Font to NF and see if it works?

Thanks, ill try.

**Comment by chupy35** [comment] 2018-11-23 20:16
> I installed the full zip package of the patched Fira (Fura) Code, and got the same problem.
> 
> However, I found a fix. In my font browser, it shows both Fura Code Nerd Font and Fura Code NF. Originally, I selected the former, and the folders did not show. But when I tried the latter font, and it works. Maybe you can try abbreviating Nerd Font to NF and see if it works?

When changing to abreviation NF shows the folders but now the other files dont have icons haha.

**Comment by Daniel-Liu-c0deb0t** [comment] 2018-11-23 20:20
For me it worked for all folders and files. Maybe you should somehow combine them? I'm out of ideas.

**Comment by chupy35** [comment] 2018-11-24 18:57
> For me it worked for all folders and files. Maybe you should somehow combine them? I'm out of ideas.

I just discover is about Font Size defined in .Xdefaults, in some sizes its displayed and in some not.

**Comment by pshoultz** [comment] 2018-12-08 18:50
I can't see any icons at all.

devicons.py is in ~/.config/ranger
devicons_linemode.py is in ~/.config/ranger/plugins/
my termite config file has: font = SauceCodePro Nerd Font 11
run ranger.  the linemode devicons and no icons are present.  Just some blank spaces for where the icons would be.
when I open up devicons.py , my icons are visible inside of vim.

I have a similar program that operates inside vim where it displays fonts so I know the icons work

**Comment by alexanderjeurissen** [comment] 2018-12-18 22:31
@pshoultz can you file a separate issue for this ? I'm closing out this issue du eto @chupy35 issue being resolved.

**Closed by alexanderjeurissen** 2018-12-18 22:31 UTC
