### ISSUE TITLE
Invalid linemode: devicons

### ISSUE THREAD

**Issue by TyNguyen2001** [alexanderjeurissen/ranger_devicons#62] opened 2020-06-28 14:19 UTC
Hello, I have encountered the following error. It seems ranger_devicons doesn't work. Please help me. Thanks!
![Screenshot from 2020-06-28 21-17-15](https://user-images.githubusercontent.com/64082226/85950111-0726e580-b985-11ea-84f7-f7bb278de4be.png)
My `rc.conf`
>set preview_images 
set preview_images_method kitty
default_linemode devicons

**Comment by f-koehler** [comment] 2020-06-30 08:52
I had the same problem. It seems that the issue is hat there is no `__init__.py` present.
As far as I can tell the author of this plugin fixed it in a02271228a9482116cf308766806d5de3d124fda.

For me checking out either that commit or the `fix_incorrect_init` resolved the issue. I assume this will merged into the main branch soon.

**Comment by alexanderjeurissen** [comment] 2020-06-30 09:51
Thanks for flagging, seemed I forgot to merge the fix above to the `main` branch.

I'll do that now.

**Closed** 2020-06-30 09:52 UTC
